NOTE: The Docker container is still in beta but is stable for production use.

=== Installation (Docker)

===== Prerequisites

- Server with Docker installed (https://docs.docker.com/engine/install/[see instructions here])

===== Installation

NOTE: The following instructions installs OpenMicroanatomy to `/opt/openmicroanatomy` using `sudo` -- feel free to customize this if you know what you're doing.

1. `cd /opt/ && sudo mkdir openmicroanatomy && cd openmicroanatomy`
2. Download the OpenMicroanatomy Docker configuration: `sudo wget https://raw.githubusercontent.com/openmicroanatomy/hosting/main/docker-compose.yml`
3. Start the server for the first time using `sudo docker-compose run server`
    - If you get a _**AccessDeniedException**_ error try running `sudo chmod 777 server-data` and retry the previous command.
    - This error is due to *OpenMicroanatomy* running inside the Docker container as the user `oma` which does not have the permissions to modify that folder. If you require stricter security, create a user called `oma` on the host machine and assign permissions to that user to `server-data` folder.
4. Follow the instructions to create the initial organization and administrator account _(these can be edited later; see *Chapters:* <<Users & Roles>> and <<Organizations>>)_
5. After creating the initial organization and administrator account stop the server by inputting `stop` into the terminal or by pressing `CTRL + A` + `CTRL + C` to exit.
6. Edit the `application.conf` inside `server-data` using e.g. `nano` (e.g. `nano server-data/application.conf`)
    - The most important step is to configure `server.host` to match your hostname (see *Chapter:* <<SSL>> for further instructions); otherwise slides _will not work_ and fixing them later is can be cumbersome -- see <<Fixing Incorrect Slide Paths>>.
    - See <<Configuration>> chapter below for more details about different configuration options.
6. Start the server using `sudo docker-compose up -d`; to stop the server run `sudo docker-compose down --remove-orphans`.

===== Updating

OpenMicroanatomy uses semantic versioning `MAJOR.MINOR.PATCH`, meaning no breaking changes happen unless the major version changes (e.g. from 1.X.X to 2.X.X). If you're using `:latest` (default) as the Docker container version you may accidentally update to a newer major version. It is recommended that you pin your version to e.g. `:v1` to allow minor and patch upgrades or `v1.1` to allow only patches by editing  `docker-compose.yml`.

To update OpenMicroanatomy Server, run the following commands.

1. `docker-compose down`
2. `docker pull openmicroanatomy`
3. `docker-compose up -d`

=== Configuration

Configuration is available at `application.conf` which will be generated during the initial start-up, it contains comments for instructions. The default configuration has sensible defaults, but you're free to tweak anything you wish.

The *only required configuration step* is setting the `server.host` parameter -- this should point to your hostname (see <<SSL>> chapter). *Your server _will not_ function properly if you do not set the host parameter.*

For storing the tiles there are two options. *Local (default)* storage uses the servers disk to store any tiles. For *Cloud storage* currently *https://docs.csc.fi/data/Allas/[CSC Allas]* is only supported, with initial support for *Amazon S3* existing. If you're interested in support for https://aws.amazon.com/s3/[Amazon S3] or any other cloud provider, please create a https://github.com/openmicroanatomy/server/issues[GitHub issue] regarding this.

To *generate a new configuration* simply delete the old one and restart the server. To *reload the configuration* you must restart the server.

=== SSL

OpenMicroanatomy includes SSL support using https://caddyserver.com/[Caddy] with Docker. You're free to manually setup a *reverse proxy* using software such as https://caddyserver.com/[Caddy], https://www.nginx.com/[nginx] or https://httpd.apache.org/[Apache] to provide a secure connection.

==== Setting up SSL using Caddy server with Docker

1. Shutdown any Docker instances: `sudo docker-compose down` (running inside `/opt/openmicroanatomy`)
2. Download the _Caddy Docker configuration_ using `sudo wget https://raw.githubusercontent.com/openmicroanatomy/hosting/main/docker-compose.caddy.yml`
3. Edit the _Caddy Docker configuration_: `sudo nano docker-compose.caddy.yml`
4. Change `virtual.host` to your domain name without `https://` e.g.: `virtual.host: 'example.com'`
5. Change `virtual.tls-address` to your administrator email account e.g. `virtual.tls-address: 'john.smith@example.com'` -- this is not revealed to anyone and only used by CertBot to notify about any issues with the SSL certificate.
6. **Save and exit **
7. Edit the _OpenMicroanatomy Docker configuration_: `sudo nano docker-compose.yml`
8. Under `ports` change `- '7777:7777'` to `- '127.0.0.1:7777:7777` to prohibit access using insecure HTTP
9. **Save and exit**
10. Run `sudo docker-compose -f docker-compose.yml -f docker-compose.caddy.yml up -d` to restart server with SSL.
11. *Done*: OpenMicroanatomy should be accessible via `https://example.com`

==== Reverse proxy

If your DNS includes an automatic SSL proxy option, feel free to try that. Alternatively you can setup / configure your existing Apache / nginx server to behave as a reverse proxy for OpenMicroanatomy.

Below is an example nginx reverse proxy configuration using https://certbot.eff.org/[Certbot].

```
server {
    server_name open.microanatomy.server;

    access_log /var/log/nginx/reverse-access.log;
    error_log /var/log/nginx/reverse-error.log;

    include /etc/nginx/conf/proxy.conf;

    location / {
        proxy_pass http://127.0.0.1:7777;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/open.microanatomy.server/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/open.microanatomy.server/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = open.microanatomy.server) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;

    server_name open.microanatomy.server;
    return 404;
}
```

=== Installation (Manually)

WARNING: Manual OpenMicroanatomy installations are not recommended. Assistance for any issues with manual installations *cannot be guaranteed*.

===== Prerequisites

- Server with Java 19 or later installed

===== Installation

_These instructions assume you're familiar with Linux already and skips multiple crucial steps such as creating a new user._

It's advised to create a separate user, such as `openmicroanatomy` and to use software such as `screen` to create separate sessions for both instances.

1. Download the latest `open-microanatomy-server.jar` from https://github.com/openmicroanatomy/server/releases[GitHub].
2. Save it to e.g. `/home/openmicroanatomy/server/open-microanatomy-server.jar`
3. Extract OpenSlide Binaries
- _these are currently only available from the https://github.com/qupath/qupath/tree/main/maven/repo/org/openslide/openslide/3.4.1_2[QuPath repository] -- download the `.jar` file specific to your operating system and *extract* it to where you saved `qupath-edu-server.jar`._

===== Running the server

1. Start the server with `java -jar <jar> [-port <port>]`
2. During your initial start-up, you will create your first administrator account.

===== Updating

Download the latest `open-microanatomy-server.jar` from GitHub and restart any running `screen`.

===== Systemd service

To start OpenMicroanatomy automatically or restart it in case the process gets killed, you can create a *Systemd* service for it.

=== Troubleshooting

==== Fixing Incorrect Slide Paths

Uploading slides with an incorrect `server.path` inside `application.conf` will result in QuPath and OpenMicroanatomy Cloud not knowing where the slides are actually stored and making them inaccessible. The `server.path` is encoded within each slides `.properties` file when uploaded, thus requiring them to be manually updated if the `server.path` is changed.

To check for any incorrect paths run the following command in the server root directory.

`cd slides && cat *.properties || grep "<your previous server.path>"`

---

1. Backup slides: `cp -R slides slides-backup`
2. Switch to slides directory: `cd slides`
3. Perform a Search & Replace: `sed -i -- 's/<previous server.path>/<new server.path>/g' *`
4. Validate that all instances have been replaced: `cat *.properties || grep "<your previous server.path>"``

=== HTTP API

OpenMicroanatomy Server includes a *REST API* -- documentation is available https://demo.edu.qupath.yli-hallila.fi/swagger[here].
